language: node_js

node_js: 0.10

services:
  - mongodb
  - elasticsearch


branches:
  only:
    - master

addons:
  hosts:
    - localhost

before_install:
  - sudo apt-get update && sudo apt-get install sendmail

before_script:
  - npm install -g grunt-cli
  - sleep 10

script:
  - grunt coverage

